# Run these commands before running the script
docker run -d -p 14022:22 -p 9000:9000 -p 14240:14240 --name tigergraph --ulimit nofile=1000000:1000000 -t tigergraph/tigergraph:latest
#docker exec -it tigergraph bash -c "gadmin start all"
docker exec -it tigergraph /bin/bash
gadmin start all
gadmin license set eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJJc3N1ZXIiOiJUaWdlckdyYXBoIEluYy4iLCJBdWRpZW5jZSI6IlRpZ2VyR3JhcGggRnJlZSIsIlN0YXJ0VGltZSI6MTcyNjE1NDYzOSwiRW5kVGltZSI6MTcyODc1MDIzOSwiSXNzdWVUaW1lIjoxNzI2MTU4MjM5LCJFZGl0aW9uIjoiRW50ZXJwcmlzZSIsIlZlcnNpb24iOiJBbGwiLCJIb3N0Ijp7Ik1heENQVUNvcmUiOjEwMDAwMDAwMDAwMDAwMDAsIk1heFBoeXNpY2FsTWVtb3J5Qnl0ZXMiOjEwMDAwMDAwMDAwMDAwMDAsIkFsbG93ZWRIYXJkd2FyZVNpZ25hdHVyZXMiOltdLCJBbGxvd2VkT1NTaWduYXR1cmVzIjpbXSwiTWF4Q2x1c3Rlck5vZGVOdW1iZXIiOjEwMjQsIkFsbG93ZWRBenVyZUluc3RhbmNlSUQiOltdLCJBbGxvd2VkR0NQSW5zdGFuY2VJRCI6W10sIkFsbG93ZWRBV1NJbnN0YW5jZUlEIjpbXX0sIlRvcG9sb2d5Ijp7Ik1heFZlcnRleE51bWJlciI6MTAwMDAwMDAwMDAwMDAwMCwiTWF4RWRnZU51bWJlciI6MTAwMDAwMDAwMDAwMDAwMCwiTWF4R3JhcGhOdW1iZXIiOjEwMjQsIk1heFRvcG9sb2d5Qnl0ZXMiOjUzNjg3MDYzNzEyfSwiR1BFIjpudWxsLCJHU0UiOm51bGwsIkdTVCI6eyJFbmFibGUiOnRydWV9LCJNTFdCIjpudWxsLCJJbnNpZ2h0cyI6eyJFbmFibGUiOnRydWV9LCJHU1FMU2hlbGwiOnsiRW5hYmxlIjp0cnVlfSwiR3JhcGhRTCI6eyJFbmFibGUiOnRydWV9LCJSdW50aW1lTWVtb3J5Ijp7IlByb2Nlc3NSU1MiOm51bGwsIk1heFVzZXJSZXNpZGVudFNldEJ5dGVzIjoxMDAwMDAwMDAwMDAwMDAwfSwiUGVuYWx0eSI6bnVsbH0.ALVMdptmYBWxZpkerZwSbdp4rYFixd-uI1_uqJ6buPnXluxFALNmtNfvFiXd8x-0h0KkQyZOlKAogxu2FKxhmvumKyj6o6BSnV7VQ2s-bGpgranpBCRxTe9hXa5A5r1x_4ow_lWWTaFYU5aMgZhh-3r7pMNUfOsmVRlJawjKLJRrl1yVyaKJkhxQYscCaRJ3oo33Py1ZLCx8DbY992mng1rtBfnN2X-yFDjemudsLrIeuKKxG28gFsVSyuBkGL-L5VTaHR-POOgV_N2No60VJfCgMth90AvVjmHasuOrLGkBirXfLorWkw0lAWKKlJZW3MOBt6mIS_2YbUSKSCOlog
gadmin config apply
gadmin license status

# gsql -u tigergraph
# CREATE VERTEX User (PRIMARY_ID id UINT)
# CREATE UNDIRECTED EDGE FRIENDS_WITH (FROM User, TO User)
# CREATE GRAPH facebook(User, FRIENDS_WITH)
# INSTALL DATASET

# gsql -u tigergraph -g facebook
# CREATE SECRET facebook
# SHOW SECRET

# Copy users.csv and edges.csv into TigerGraph container
docker cp ../memgraph/users.csv tigergraph:/home/tigergraph/tigergraph/data/gsql/users.csv
docker cp ../memgraph/edges.csv tigergraph:/home/tigergraph/tigergraph/data/gsql/edges.csv

# gadmin show user
# http://localhost:14240
# pip install pyTigerGraph


